### PR TITLE
#162809348 Add New Environment Variables

### PR DESCRIPTION
**Pull request by HarithJ**
#### What does this PR do?
- Adds new environment variable; TRAVEL_READINESS_MAIL_CYCLE

#### Description of Task to be completed?
There are two new environment variables;
`TRAVEL_READINESS_MAIL_CYCLE`
`SURVEY_URL`

#### How should this be manually tested?
N/A

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/162809348
https://www.pivotaltracker.com/story/show/162809346

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

### CODE REVIEW

**Comment by samuelkubai** [comment]
@HarithJ you should request review for the individual standing in for @orezi

**Comment by HarithJ** [comment]
> @HarithJ you should request review for the individual standing in for @orezi

I couldn't find him in the `reviewers` list @samuelkubai, but I mentioned him in a message.

**Comment by inno-asiimwe** [comment]
@samuelkubai I have reviewed this and LGTM.

**Comment by samuelkubai** [comment]
> @samuelkubai I have reviewed this and LGTM.

For some reason, your review is not activating the merge button.

**Pull request merged**
